export const videoPlayerCopy = {
  unsupported: 'Ihr Browser unterstützt das Video-Element nicht.',
  region: 'Videoplayer',
  play: 'Abspielen',
  pause: 'Pausieren',
  replay: 'Erneut abspielen',
  seekSlider: 'Wiedergabeposition',
  elapsedOfTotal: (elapsed: string, total: string) => `${elapsed} von ${total}`,
  mute: 'Ton aus',
  unmute: 'Ton ein',
  volume: 'Lautstärke',
  enterFullscreen: 'Vollbild',
  exitFullscreen: 'Vollbild beenden',
  speed: 'Wiedergabegeschwindigkeit',
  speedOption: (rate: number) => `${rate.toString().replace('.', ',')}×`,
  normalSpeedSuffix: 'Normal',
  chapter: 'Kapitel',
} as const
