VALID_ASSIGNMENTS = {"control", "experimental"}

CONTROL_SUBGROUP = "control"
EXPERIMENTAL_SUBGROUPS = ("standard", "enhanced-player")

LEARNING_CONDITION_LABELS = (CONTROL_SUBGROUP, *EXPERIMENTAL_SUBGROUPS)

VALID_SUBGROUPS = {CONTROL_SUBGROUP, *EXPERIMENTAL_SUBGROUPS}
VALID_SUBGROUPS_BY_ASSIGNMENT = {
    "control": {CONTROL_SUBGROUP},
    "experimental": set(EXPERIMENTAL_SUBGROUPS),
}

LEARNING_CONDITION_TARGET_WEIGHTS = {
    CONTROL_SUBGROUP: 2.0,
    EXPERIMENTAL_SUBGROUPS[0]: 1.0,  # standard
    EXPERIMENTAL_SUBGROUPS[1]: 1.0,  # enhanced
}

_PRIOR_PROGRAMMING_EXPERIENCE_SCORE_MIN = 0
_PRIOR_PROGRAMMING_EXPERIENCE_SCORE_MAX = 6
PRIOR_PROGRAMMING_EXPERIENCE_SCORE_RANGE = (
    _PRIOR_PROGRAMMING_EXPERIENCE_SCORE_MAX - _PRIOR_PROGRAMMING_EXPERIENCE_SCORE_MIN
)

SCORE_IMBALANCE_WEIGHT = 1.0

ALLOCATION_IMBALANCE_TOLERANCE = 1e-9

EFRON_BIASED_COIN_PROBABILITY = 0.75
