export type Page =
  | 'welcome'
  | 'consent'
  | 'demographics'
  | 'adhdScreening'
  | 'prePanas'
  | 'ready'
  | 'fam'
  | 'preQuiz'
  | 'control'
  | 'experimental'
  | 'postPanas'
  | 'ues'
  | 'followUp'
  | 'feedback'
  | 'thankYou'
